services:
  weaviate:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: cr.weaviate.io/semitechnologies/weaviate:latest
    ports:
    - 8080:8080
    - 50051:50051
    volumes:
    - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_MODULES: 'text2vec-ollama,generative-ollama'
      CLUSTER_HOSTNAME: 'node1'
      OLLAMA_API_ENDPOINT: ${OLLAMA_API_ENDPOINT}
    depends_on:
      ollama-healthcheck:
        condition: service_healthy

  ollama-healthcheck:
    image: curlimages/curl:latest
    environment:
      OLLAMA_API_ENDPOINT: ${OLLAMA_API_ENDPOINT}
    command: ["sh", "-c", "while true; do sleep 3600; done"]
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "curl -sf $$OLLAMA_API_ENDPOINT || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  weaviate_data:
